
package wsproxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>中国电视节目预告 Web 服务</strong>，数据准确可靠，提供全国近800个电视台一个星期节目预告数据。<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> 和/或其各供应商不为本页面提供信息的错误、残缺、延迟或因依靠此信息所采取的任何行动负责。</br>中国电视节目预告Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChinaTVprogramWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/D:/workspace/git/CS-Study/\u5206\u5e03\u5f0f\u8ba1\u7b97/exp4/ChinaTVprogramWebService.asmx")
public class ChinaTVprogramWebService
    extends Service
{

    private final static URL CHINATVPROGRAMWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHINATVPROGRAMWEBSERVICE_EXCEPTION;
    private final static QName CHINATVPROGRAMWEBSERVICE_QNAME = new QName("http://WebXml.com.cn/", "ChinaTVprogramWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/git/CS-Study/\u5206\u5e03\u5f0f\u8ba1\u7b97/exp4/ChinaTVprogramWebService.asmx");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHINATVPROGRAMWEBSERVICE_WSDL_LOCATION = url;
        CHINATVPROGRAMWEBSERVICE_EXCEPTION = e;
    }

    public ChinaTVprogramWebService() {
        super(__getWsdlLocation(), CHINATVPROGRAMWEBSERVICE_QNAME);
    }

    public ChinaTVprogramWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHINATVPROGRAMWEBSERVICE_QNAME, features);
    }

    public ChinaTVprogramWebService(URL wsdlLocation) {
        super(wsdlLocation, CHINATVPROGRAMWEBSERVICE_QNAME);
    }

    public ChinaTVprogramWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHINATVPROGRAMWEBSERVICE_QNAME, features);
    }

    public ChinaTVprogramWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChinaTVprogramWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChinaTVprogramWebServiceSoap
     */
    @WebEndpoint(name = "ChinaTVprogramWebServiceSoap")
    public ChinaTVprogramWebServiceSoap getChinaTVprogramWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaTVprogramWebServiceSoap"), ChinaTVprogramWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChinaTVprogramWebServiceSoap
     */
    @WebEndpoint(name = "ChinaTVprogramWebServiceSoap")
    public ChinaTVprogramWebServiceSoap getChinaTVprogramWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "ChinaTVprogramWebServiceSoap"), ChinaTVprogramWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHINATVPROGRAMWEBSERVICE_EXCEPTION!= null) {
            throw CHINATVPROGRAMWEBSERVICE_EXCEPTION;
        }
        return CHINATVPROGRAMWEBSERVICE_WSDL_LOCATION;
    }

}
