
package wsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChinaTVprogramWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChinaTVprogramWebServiceSoap {


    /**
     * <br /><h3>[第一步] 获得支持的省市（地区）和分类电视列表 DataSet</h3><p>输入参数：无；返回数据：DataSet，结构为：Item(areaID)=省市和分类电视ID，Ietm(Area)=省市和分类电视名称，Item(Zone)=所属地区。</p><br />
     * 
     * @return
     *     returns wsproxy.GetAreaDataSetResponse.GetAreaDataSetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getAreaDataSet")
    @WebResult(name = "getAreaDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getAreaDataSet", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetAreaDataSet")
    @ResponseWrapper(localName = "getAreaDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetAreaDataSetResponse")
    public wsproxy.GetAreaDataSetResponse.GetAreaDataSetResult getAreaDataSet();

    /**
     * <br /><h3>[第一步] 获得支持的省市（地区）和分类电视名称 String()</h3><p>输入参数：无；返回数据：一个一维字符串数组 String()，结构为：省市和分类电视ID@省市和分类电视名称@所属地区。</p><br />
     * 
     * @return
     *     returns wsproxy.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getAreaString")
    @WebResult(name = "getAreaStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getAreaString", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetAreaString")
    @ResponseWrapper(localName = "getAreaStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetAreaStringResponse")
    public ArrayOfString getAreaString();

    /**
     * <br /><h3>[第二步] 通过省市ID或分类电视ID获得电视台列表 DataSet</h3><p>输入参数：theAreaID = 省市ID或分类电视ID（Integer）；返回数据：DataSet，结构为：Item(tvStationID)=电视台ID，Ietm(tvStationName)=电视台名称。</p><br />
     * 
     * @param theAreaID
     * @return
     *     returns wsproxy.GetTVstationDataSetResponse.GetTVstationDataSetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVstationDataSet")
    @WebResult(name = "getTVstationDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVstationDataSet", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVstationDataSet")
    @ResponseWrapper(localName = "getTVstationDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVstationDataSetResponse")
    public wsproxy.GetTVstationDataSetResponse.GetTVstationDataSetResult getTVstationDataSet(
        @WebParam(name = "theAreaID", targetNamespace = "http://WebXml.com.cn/")
        int theAreaID);

    /**
     * <br /><h3>[第二步] 通过省市ID或分类电视ID获得电视台名称 String()</h3><p>输入参数：theAreaID = 省市ID或分类电视ID（Integer）；返回数据：一个一维字符串数组 String()，结构为：电视台ID@电视台名称。</p><br />
     * 
     * @param theAreaID
     * @return
     *     returns wsproxy.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVstationString")
    @WebResult(name = "getTVstationStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVstationString", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVstationString")
    @ResponseWrapper(localName = "getTVstationStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVstationStringResponse")
    public ArrayOfString getTVstationString(
        @WebParam(name = "theAreaID", targetNamespace = "http://WebXml.com.cn/")
        int theAreaID);

    /**
     * <br /><h3>[第三步] 通过电视台ID获得该电视台频道列表 DataSet</h3><p>输入参数：theTVstationID = 电视台ID（Integer）；返回数据：DataSet，结构为：Item(tvChannelID)=频道ID，Ietm(tvChannel)=频道名称。</p><br />
     * 
     * @param theTVstationID
     * @return
     *     returns wsproxy.GetTVchannelDataSetResponse.GetTVchannelDataSetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVchannelDataSet")
    @WebResult(name = "getTVchannelDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVchannelDataSet", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVchannelDataSet")
    @ResponseWrapper(localName = "getTVchannelDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVchannelDataSetResponse")
    public wsproxy.GetTVchannelDataSetResponse.GetTVchannelDataSetResult getTVchannelDataSet(
        @WebParam(name = "theTVstationID", targetNamespace = "http://WebXml.com.cn/")
        int theTVstationID);

    /**
     * <br /><h3>[第三步] 通过电视台ID获得该电视台频道名称 String()</h3><p>输入参数：theTVstationID = 电视台ID（Integer）；返回数据：一个一维字符串数组 String()，结构为：频道ID@频道名称。</p><br />
     * 
     * @param theTVstationID
     * @return
     *     returns wsproxy.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVchannelString")
    @WebResult(name = "getTVchannelStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVchannelString", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVchannelString")
    @ResponseWrapper(localName = "getTVchannelStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVchannelStringResponse")
    public ArrayOfString getTVchannelString(
        @WebParam(name = "theTVstationID", targetNamespace = "http://WebXml.com.cn/")
        int theTVstationID);

    /**
     * <br /><h3>[第四步] 通过频道ID获得该频道节目列表 DataSet</h3><p>输入参数：theTVchannelID = 频道ID（Integer），theDate=日期（String 格式：yyyy-MM-dd，如：2007-07-02，空则默认当天），userID=商业用户ID（String 免费用户不需要）；返回数据：DataSet，结构为：Item(playTime)=播出时间，Ietm(meridiem)=PM或AM，Ietm(tvProgram)=节目信息，Item(tvStationInfo)=电视台信息。</p><br />
     * 
     * @param theDate
     * @param theTVchannelID
     * @param userID
     * @return
     *     returns wsproxy.GetTVprogramDateSetResponse.GetTVprogramDateSetResult
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVprogramDateSet")
    @WebResult(name = "getTVprogramDateSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVprogramDateSet", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVprogramDateSet")
    @ResponseWrapper(localName = "getTVprogramDateSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVprogramDateSetResponse")
    public wsproxy.GetTVprogramDateSetResponse.GetTVprogramDateSetResult getTVprogramDateSet(
        @WebParam(name = "theTVchannelID", targetNamespace = "http://WebXml.com.cn/")
        int theTVchannelID,
        @WebParam(name = "theDate", targetNamespace = "http://WebXml.com.cn/")
        String theDate,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

    /**
     * <br /><h3>[第四步] 通过频道ID获得该频道节目 String()</h3><p>输入参数：theTVchannelID = 频道ID（Integer），theDate=日期（String 格式：yyyy-MM-dd，如：2007-07-02，空则默认当天），userID=商业用户ID（String 免费用户不需要）；返回数据：一个一维字符串数组 String()，结构为：播出时间(AM or PM)@@@节目信息@@@电视台信息。</p><br />
     * 
     * @param theDate
     * @param theTVchannelID
     * @param userID
     * @return
     *     returns wsproxy.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getTVprogramString")
    @WebResult(name = "getTVprogramStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getTVprogramString", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVprogramString")
    @ResponseWrapper(localName = "getTVprogramStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "wsproxy.GetTVprogramStringResponse")
    public ArrayOfString getTVprogramString(
        @WebParam(name = "theTVchannelID", targetNamespace = "http://WebXml.com.cn/")
        int theTVchannelID,
        @WebParam(name = "theDate", targetNamespace = "http://WebXml.com.cn/")
        String theDate,
        @WebParam(name = "userID", targetNamespace = "http://WebXml.com.cn/")
        String userID);

}
